[package]
name = "n_player"
version.workspace = true
authors = ["Enn3Developer <arturpeshko39@gmail.com>"]
edition = "2021"
repository = "https://github.com/Enn3Developer/n_music"
description = "UI-agnostic core of N Music, a simple music player written in Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib"]

[dependencies]
bitcode = { version = "0.6", features = ["derive"] }
n_audio = { path = "../n_audio" }
n_event_bus = { path = "../n_event_bus" }
rand = "0.10"
multitag = "0.4"
zune-image = { version = "0.5", default-features = false, features = ["png", "jpeg", "jpeg-xl", "bmp", "threads"] }
zune-imageprocs = "0.5.1"
zune-core = { version = "=0.5.1", default-features = false, features = ["std"] }
rimage = { version = "0.12.0", default-features = false, features = ["mozjpeg", "resize", "threads", "webp"] }
tempfile = "3.20"
tokio = { version = "1.45", features = ["macros", "rt", "rt-multi-thread", "sync", "time"] }
infer = { version = "0.22", default-features = false, features = ["std"] }
zstd = "0.14"
async-trait = "0.1"

[target.'cfg(not(target_os = "android"))'.dependencies]
directories = "6.0"
