[workspace]
resolver = "2"
members = [
    "n_music_core",
    "n_music_desktop",
    "n_music_android",
    "n_event_bus",
]
default-members = [
    "n_music_core",
    "n_music_desktop",
    "n_event_bus",
]

[workspace.package]
version = "2.0.0-alpha.11"

[profile.dev]
opt-level = 1

[profile.release]
lto = true
codegen-units = 1
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release.build-override]
opt-level = 3
