import {
    MaterialText,
    MaterialTypography,
    MaterialPalette,
    MaterialStyleMetrics
} from "../../material-1.0/material.slint";

export component Setting {
    in property <string> text;
    in property <string> supporting_text;

    min-height: MaterialStyleMetrics.size_56;

    HorizontalLayout {
        spacing: MaterialStyleMetrics.spacing_16;
        alignment: space-between;

        VerticalLayout {
            alignment: center;
            horizontal-stretch: 1;
            min-width: 0px;

            MaterialText {
                text: root.text;
                style: MaterialTypography.body_large;
                color: MaterialPalette.on_surface;
                wrap: word-wrap;
            }

            if root.supporting_text != "": MaterialText {
                text: root.supporting_text;
                style: MaterialTypography.body_medium;
                color: MaterialPalette.on_surface_variant;
                wrap: word-wrap;
            }
        }

        HorizontalLayout {
            alignment: center;
            spacing: MaterialStyleMetrics.spacing_8;
            @children
        }
    }
}
