import { Localization } from "../globals/localization.slint";
import { AppData } from "../globals/app_data.slint";
import { SearchBar } from "search_bar.slint";
import {
    MaterialStyleMetrics,
    IconButton,
    FilledIconButton,
    LinearProgressIndicator
} from "../../material-1.0/material.slint";

export component TopPanel {
    callback settings();

    VerticalLayout {
        padding: MaterialStyleMetrics.padding_10;
        padding-top: 32px;
        spacing: 10px;

        HorizontalLayout {
            height: MaterialStyleMetrics.size_56;
            spacing: MaterialStyleMetrics.spacing_8;

            SearchBar {
                horizontal-stretch: 1;
                min-width: 0px;
                placeholder-text: Localization.search;
                leading_icon: @image-url("../../assets/icons/search.svg");
                text <=> AppData.search_text;

                edited(value) => {
                    AppData.searching(value);
                }
                accepted(value) => {
                    AppData.searching(value);
                    self.clear-focus();
                }
            }

            IconButton {
                icon: @image-url("../../assets/icons/down.svg");
                accessible-label: "Show playing track";
                clicked => {
                    AppData.scroll();
                }
            }

            FilledIconButton {
                icon: @image-url("../../assets/icons/settings.svg");
                accessible-label: Localization.settings;
                clicked => {
                    root.settings();
                }
            }
        }

        LinearProgressIndicator {
            progress: AppData.progress;
        }
    }
}
