import {TrackData} from "./../data/track_data.slint";
import { Slider, Button } from "std-widgets.slint";
import { AppData } from "../globals/app_data.slint";

export component ControlPanel {
    control-panel := HorizontalLayout {
        spacing: 10px;
        padding: 10px;
        Image {
            width: 72px;
            height: 72px;
            source: AppData.playing_track.cover;
        }

        VerticalLayout {
            HorizontalLayout {
                spacing: 10px;
                alignment: end;
                Text {
                    vertical-alignment: center;
                    text: AppData.position_time;
                }

                Slider {
                    minimum: 0.0;
                    maximum: AppData.length > 1.0 ? AppData.length : 1.0;
                    width: control-panel.width * 24%;
                    value <=> AppData.time;
                    changed(value) => {
                        AppData.seek(value);
                    }
                }

                Text {
                    vertical-alignment: center;
                    text: AppData.playing_track.time;
                }

                Slider {
                    minimum: 0.0;
                    maximum: 1.0;
                    width: control-panel.width * 24%;
                    value: AppData.volume;
                    changed(value) => {
                        AppData.set_volume(value)
                    }
                }

                Text {
                    vertical-alignment: center;
                    text: round(AppData.volume * 100.0) + "%";
                }
            }

            HorizontalLayout {
                VerticalLayout {
                    alignment: center;
                    Text {
                        text: AppData.playing_track.title;
                        overflow: elide;
                        font-size: 12px;
                        max-width: control-panel.width * 40%;
                    }

                    Text {
                        text: AppData.playing_track.artist;
                        overflow: elide;
                        font-size: 12px;
                        max-width: control-panel.width * 40%;
                    }
                }

                HorizontalLayout {
                    alignment: end;
                    spacing: 10px;
                    Button {
                        icon: @image-url("../../assets/icons/previous.svg");
                        colorize-icon: true;
                        clicked => {
                            AppData.play_previous()
                        }
                    }

                    Button {
                        icon: AppData.playback ? @image-url("../../assets/icons/pause.svg") : @image-url("../../assets/icons/play.svg");
                        colorize-icon: true;
                        clicked => {
                            AppData.toggle_pause()
                        }
                    }

                    Button {
                        icon: @image-url("../../assets/icons/next.svg");
                        colorize-icon: true;
                        clicked => {
                            AppData.play_next()
                        }
                    }
                }
            }
        }
    }
}
