export component Setting {
    in property <string> text;
    HorizontalLayout {
        max-height: 20px;
        Text {
            horizontal-alignment: left;
            vertical-alignment: center;
            text: text;
            font-size: 14px;
        }

        HorizontalLayout {
            alignment: end;
            max-height: parent.max-height;
            spacing: 10px;
            @children
        }
    }
}
