import { Button, ProgressIndicator, LineEdit, Palette } from "std-widgets.slint";
import { Localization } from "../globals/localization.slint";
import { AppData } from "../globals/app_data.slint";

export component TopPanel {
    callback settings();
    VerticalLayout {
        spacing: 10px;
        padding: 10px;
        padding-bottom: 5px;
        HorizontalLayout {
            spacing: 10px;
            LineEdit {
                placeholder-text: Localization.search;
                edited(value) => {
                    AppData.searching(value)
                }
            }

            Button {
                icon: @image-url("../../assets/icons/settings.svg");
                colorize-icon: true;
                clicked => {
                    settings()
                }
            }
        }

        ProgressIndicator {
            progress <=> AppData.progress;
        }
    }
}
