import {TrackData} from "./../data/track_data.slint";
import {Separator} from "./../components/separator.slint";
import {TopPanel} from "./../components/top_panel.slint";
import {ControlPanel} from "./../components/control_panel.slint";
import {Track} from "./../components/track.slint";
import {ListView, ScrollView} from "std-widgets.slint";
import { AppData } from "../globals/app_data.slint";

export component App {
    callback settings();
    VerticalLayout {
        top-panel := TopPanel {
            settings => {
                settings()
            }
        }

        ScrollView {
            viewport-width: parent.width - 20px;
            viewport-y <=> AppData.viewport-y;
            VerticalLayout {
                for track[i] in AppData.tracks: Track {
                    height: track.visible ? 84px : 0px;
                    track: track;
                    playing: AppData.playing == track.index;
                    clicked => {
                        AppData.clicked(track.index);
                    }
                }
            }
        }

        Separator {
            padding-top: 5px;
        }

        control_panel := ControlPanel {
            width: parent.width;
        }
    }
}
