import {TrackData} from "./../data/track_data.slint";
import {Separator} from "./../components/separator.slint";
import {TopPanel} from "./../components/top_panel.slint";
import {ControlPanel} from "./../components/control_panel.slint";
import {Track} from "./../components/track.slint";
import {ListView} from "std-widgets.slint";
import { AppData } from "../globals/app_data.slint";

export component App {
    callback settings();
    VerticalLayout {
        top-panel := TopPanel {
            settings => {
                settings()
            }
        }

        ListView {
            viewport-width: parent.width - 20px;
            for track[i] in AppData.tracks: Track {
                track: track;
                playing: AppData.playing == track.index;
                clicked => {
                    AppData.clicked(track.index)
                }
            }
        }

        Separator {
            padding-top: 5px;
        }

        control_panel := ControlPanel {
            width: parent.width;
        }
    }
}
