[package]
name = "n_music_desktop"
version.workspace = true
edition = "2021"
authors = ["Enn3Developer <arturpeshko39@gmail.com>"]
repository = "https://github.com/Enn3Developer/n_music"
description = "Desktop entry point for N Music"

[[bin]]
name = "n_music_desktop"
path = "src/main.rs"

[build-dependencies]
cxx-qt-build = "0.10"

[dependencies]
n_music_core = { path = "../n_music_core" }
n_event_bus = { path = "../n_event_bus" }
bitflags = "2"
log = "0.4"
n_music_media_notification = { path = "../n_music_media_notification" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sys-locale = "0.3"
# Keep this in sync with vpk in .config/dotnet-tools.json.
velopack = "=1.2.0"
directories = "6.0"
cxx = "1.0"
cxx-qt = "0.10"
cxx-qt-lib = { version = "0.10", features = ["qt_gui", "qt_qml"] }
