export global Localization {
    in-out property <[string]> localizations;
    in-out property <string> current_locale;
    in-out property <string> settings;
    in-out property <string> search;
    in-out property <string> theme;
    in-out property <string> window_size;
    in-out property <string> music_path;
    in-out property <string> language;
    in-out property <string> theme_system;
    in-out property <string> theme_light;
    in-out property <string> theme_dark;
    in-out property <string> credits;
    in-out property <string> license;
    in-out property <string> update_text;
    in-out property <string> check_update;
    in-out property <string> update;
    in-out property <string> rescan;
    callback set_locale(string);
}
