[package]
resolver = "2"
name = "n_audio"
version = "1.3.0"
authors = ["Enn3Developer <arturpeshko39@gmail.com>"]
edition = "2021"
license = "GPL-3.0-only"
description = "Simple audio player"
homepage = "https://github.com/Enn3Developer/n_music"
repository = "https://github.com/Enn3Developer/n_music"
documentation = "https://docs.rs/crate/n_audio/1.1.0"
readme = "README.md"

[dev-dependencies]
nconsole = "0.4.0"

[dependencies]
symphonia = { version = "0.5.3", features = ["all"] }
symphonia-core = "0.5.3"
audiopus = "0.3.0-rc.0"
audiopus_sys = { version = "0.2.2", features = ["dynamic"] }
rand = "0.8.5"
once_cell = "1.19.0"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
rb = "0.4.0"
cpal = "0.15.2"
dasp = "0.11.0"