import { TopPanel } from "../components/top_panel.slint";
import { ControlPanel } from "../components/control_panel.slint";
import { Track } from "../components/track.slint";
import { AppData } from "../globals/app_data.slint";
import { ScrollView } from "../components/scroll_view.slint";
import { MaterialPalette } from "../../material-1.0/material.slint";

export component App {
    callback settings();

    Rectangle {
        background: MaterialPalette.background;

        VerticalLayout {
            spacing: 0px;

            TopPanel {
                settings => {
                    root.settings();
                }
            }

            ScrollView {
                viewport-width: self.visible-width - 12px;
                viewport-y <=> AppData.viewport-y;
                horizontal-scrollbar-policy: always-off;

                VerticalLayout {
                    spacing: 0px;

                    for track in AppData.tracks: Track {
                        track: track;
                        playing: AppData.playing == track.index;
                        clicked => {
                            AppData.clicked(track.index);
                        }
                    }
                }
            }

            ControlPanel { }
        }
    }
}
