import { ScrollView } from "../components/scroll_view.slint";
import {
    Switch,
    FilledIconButton,
    TonalButton,
    TextButton,
    MaterialText,
    MaterialTypography,
    MaterialPalette,
    MaterialStyleMetrics
} from "../../material-1.0/material.slint";
import { ComboBox } from "../components/combo_box.slint";
import { Setting } from "../components/setting.slint";
import { Localization } from "../globals/localization.slint";
import { SettingsData } from "../globals/settings_data.slint";
import { AppData } from "../globals/app_data.slint";

export component Settings {
    callback exit();

    Rectangle {
        background: MaterialPalette.surface;

        VerticalLayout {
            padding-top: 32px;
            padding-left: 10px;
            padding-right: 10px;
            padding-bottom: 10px;

            HorizontalLayout {
                height: MaterialStyleMetrics.size_56;
                spacing: MaterialStyleMetrics.spacing_8;

                MaterialText {
                    horizontal-stretch: 1;
                    horizontal-alignment: left;
                    vertical-alignment: center;
                    text: Localization.settings;
                    font-size: 24px;
                }

                FilledIconButton {
                    icon: @image-url("../../assets/icons/back.svg");
                    accessible-label: "Back";
                    clicked => {
                        root.exit();
                    }
                }
            }

            ScrollView {
                viewport-width: self.visible-width - 12px;
                horizontal-scrollbar-policy: always-off;

                VerticalLayout {
                    padding-top: MaterialStyleMetrics.padding_8;
                    padding-bottom: MaterialStyleMetrics.padding_24;
                    spacing: MaterialStyleMetrics.spacing_8;

                    Setting {
                        text: Localization.theme;
                        ComboBox {
                            width: 150px;
                            height: MaterialStyleMetrics.size_56;
                            accessible-label: Localization.theme;
                            model: [Localization.theme_system, Localization.theme_light, Localization.theme_dark];
                            current-index: SettingsData.theme;
                            current-value: self.model[self.current-index];
                            selected(value) => {
                                SettingsData.change_theme(self.current-index);
                            }
                        }
                    }

                    if !AppData.android: Setting {
                        text: Localization.window_size;
                        Switch {
                            checked: SettingsData.save_window_size;
                            checked_state_changed(checked) => {
                                SettingsData.save_window_size = checked;
                                SettingsData.toggle_save_window_size(checked);
                            }
                        }
                    }

                    Setting {
                        text: Localization.music_path;
                        TonalButton {
                            icon: @image-url("../../assets/icons/folder.svg");
                            accessible-label: Localization.music_path;
                            clicked => {
                                SettingsData.path();
                            }
                        }
                    }

                    Setting {
                        text: Localization.rescan;
                        TonalButton {
                            icon: @image-url("../../assets/icons/shuffle.svg");
                            accessible-label: Localization.rescan;
                            clicked => {
                                SettingsData.scan();
                            }
                        }
                    }

                    Setting {
                        text: Localization.language;
                        ComboBox {
                            width: 150px;
                            height: MaterialStyleMetrics.size_56;
                            accessible-label: Localization.language;
                            model: Localization.localizations;
                            current-value: Localization.current_locale;
                            max_displayed_items: 3;
                            selected(value) => {
                                Localization.set_locale(value);
                            }
                        }
                    }

                    VerticalLayout {
                        padding-top: MaterialStyleMetrics.padding_30;
                        spacing: MaterialStyleMetrics.spacing_4;
                        alignment: center;

                        MaterialText {
                            text: "N Music v" + AppData.version;
                            style: MaterialTypography.label_medium;
                            color: MaterialPalette.on_surface_variant;
                            horizontal-alignment: center;
                        }

                        HorizontalLayout {
                            alignment: center;
                            TextButton {
                                text: Localization.credits;
                                clicked => {
                                    AppData.open_link("https://github.com/Enn3Developer/n_music/graphs/contributors");
                                }
                            }
                        }

                        MaterialText {
                            text: Localization.license + ": GPL-3";
                            style: MaterialTypography.label_small;
                            color: MaterialPalette.outline;
                            horizontal-alignment: center;
                        }
                    }
                }
            }
        }
    }
}
