import { VerticalBox, ScrollView, ListView, Button, HorizontalBox, Slider, Palette } from "std-widgets.slint";

struct TrackData {
    title: string,
    artist: string,
    time: string,
    cover: image,
}

component Track {
    in property <TrackData> track;
    in property <bool> playing;
    callback clicked();
    TouchArea {
        clicked => {
            clicked()
        }

        Rectangle {
            background: playing ? Palette.accent-background : Palette.background;
            border-color: Palette.border;
            border-width: parent.has-hover ? 2px : 0px;
            HorizontalLayout {
                spacing: 10px;
                padding: 10px;
                padding-left: playing ? 20px : 10px;
                Image {
                    width: 64px;
                    height: 64px;
                    source: track.cover;
                }

                VerticalLayout {
                    alignment: center;
                    Text {
                        color: playing ? Palette.accent-foreground : Palette.foreground;
                        text: track.title;
                        font-size: 12px;
                    }

                    Text {
                        text: track.artist;
                        color: playing ? Palette.accent-foreground : Palette.foreground;
                        font-size: 12px;
                    }
                }

                Text {
                    text: track.time;
                    color: playing ? Palette.accent-foreground : Palette.foreground;
                    vertical-alignment: center;
                    horizontal-alignment: right;
                    font-size: 10px;
                }
            }
        }
    }
}

component ControlPanel {
    in property <TrackData> track;
    in property <bool> playback;
    in property <string> position_time;
    in property <float> time;
    in property <float> length;
    in property <float> volume;
    callback play_previous();
    callback toggle_pause();
    callback play_next();
    callback seek(float);
    callback set_volume(float);
    control-panel := HorizontalLayout {
        spacing: 10px;
        padding: 10px;
        Image {
            width: 72px;
            height: 72px;
            source: track.cover;
        }

        VerticalLayout {
            HorizontalLayout {
                spacing: 10px;
                alignment: end;
                Text {
                    vertical-alignment: center;
                    text: position_time;
                }

                Slider {
                    minimum: 0.0;
                    maximum: length;
                    width: control-panel.width * 24%;
                    value: time;
                    changed(value) => {
                        seek(value)
                    }
                }

                Text {
                    vertical-alignment: center;
                    text: track.time;
                }

                Slider {
                    minimum: 0.0;
                    maximum: 1.0;
                    width: control-panel.width * 24%;
                    value: volume;
                    changed(value) => {
                        set_volume(value)
                    }
                }

                Text {
                    vertical-alignment: center;
                    text: round(volume * 100.0) + "%";
                }
            }

            HorizontalLayout {
                VerticalLayout {
                    alignment: center;
                    Text {
                        text: track.title;
                        font-size: 12px;
                    }

                    Text {
                        text: track.artist;
                        font-size: 12px;
                    }
                }

                HorizontalLayout {
                    alignment: end;
                    spacing: 10px;
                    Button {
                        icon: @image-url("../assets/icons/previous.svg");
                        clicked => {
                            play_previous()
                        }
                    }

                    Button {
                        icon: playback ? @image-url("../assets/icons/pause.svg") : @image-url("../assets/icons/play.svg");
                        clicked => {
                            toggle_pause()
                        }
                    }

                    Button {
                        icon: @image-url("../assets/icons/next.svg");
                        clicked => {
                            play_next()
                        }
                    }
                }
            }
        }
    }
}

export component MainWindow inherits Window {
    in property <[TrackData]> tracks;
    in property <int> playing;
    in property <bool> playback;
    in property <string> position_time;
    in property <float> time;
    in property <float> length;
    in property <float> volume;
    in property <string> version;
    in property <ColorScheme> color-scheme <=> Palette.color-scheme;
    callback clicked(int);
    callback play_previous();
    callback toggle_pause();
    callback play_next();
    callback seek(float);
    callback set_volume(float);
    title: "N Music v" + version;
    preferred-width: 450px;
    preferred-height: 600px;
    min-width: 200px;
    min-height: 300px;
    VerticalLayout {
        ListView {
            viewport-width: parent.width - 20px;
            for track[i] in tracks: Track {
                track: track;
                playing: playing == i;
                clicked => {
                    clicked(i)
                }
            }
        }

        HorizontalLayout {
            alignment: center;
            padding-top: 2px;
            Rectangle {
                width: parent.width - 20px;
                height: 2px;
                background: Palette.alternate-background;
            }
        }

        control_panel := ControlPanel {
            track: tracks[playing];
            playback: playback;
            position_time: position_time;
            time: time;
            length: length;
            volume: volume;
            play_previous => {
                play_previous()
            }
            toggle_pause => {
                toggle_pause()
            }
            play_next => {
                play_next()
            }
            seek(value) => {
                seek(value)
            }
            set_volume(value) => {
                set_volume(value)
            }
        }
    }
}
